blank_issues_enabled: false

contact_links:
    - name: ❓ Question (Discussions)
      url: https://github.com/mienaiyami/collection-extension-2.0/discussions/categories/q-a
      about: "Ask a question about this extension"
